#!/bin/bash
cd /home/pi/Desktop/Jonas/TDOA-DE
/usr/local/bin/git add .
/usr/local/bin/git commit -m "Recibiendo"
/usr/local/bin/git pull --no-commit
/usr/local/bin/git add .
/usr/local/bin/git commit -m "Mandando"
/usr/local/bin/git push
